name: GitHub Release
on:
  push:
    branches:
      - release

jobs:
  # Bump the semantic version number and publishes a GitHub release
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out release tag
        uses: actions/checkout@v2

      # Bumps the version number, creates a GitHub release, and tags this branch
      # with the new version number, like `refs/tag/v1.2.3`. This tag will then
      # be used to create the Maven release.
      - name: Create Github Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
