name: Maven Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  # Publish a Maven release
  release:
    runs-on: macos-latest

    steps:
      - name: Check out release tag
        uses: actions/checkout@v2

      - name: Read version tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Run tests, lint, and generate documentation
        # Skip nativeTest for now. We support building for multiplatform, but won't support
        # deploying to iOS (native) will be supported once the new Kotlin/Native memory and
        # threading model is released.
        run: ./gradlew --no-daemon clean check dokkaHtml -x nativeTest

      - name: Push artifacts to Maven
        # This will fail if this version has already been published.
        run: ./gradlew --no-daemon --no-parallel publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          VERSION: ${{ steps.get_version.outputs.version-without-v }}

      - name: Finalize and publish Maven release
        run: ./gradlew --no-daemon closeAndReleaseRepository
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
