name: On new merge into main
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v1

      - name: Run tests, lint, and generate documentation
        # Skip nativeTest for now. We support building for multiplatform, but won't support
        # deploying to iOS (native) will be supported once the new Kotlin/Native memory and
        # threading model is released.
        run: ./gradlew --no-daemon clean check dokkaHtml -x nativeTest

      - name: Push artifacts to Maven
        # This will fail if this version has already been published.
        run: ./gradlew --no-daemon --no-parallel publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Finalize and publish Maven release
        run: ./gradlew closeAndReleaseRepository

      - name: Create Github Release
        uses: codfish/semantic-release-action@v1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
