name: On new merge into main
on: [pull_request]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v1

      - name: Run tests and lint the code
        run: ./gradlew --no-daemon clean check

      - name: Create Github Release
        uses: codfish/semantic-release-action@v1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
