name: Pull Request Checks
on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Verify Conventional Commit format
        uses: docker://aevea/commitsar:latest

  test:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set Java Version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Code Check
        # Skip nativeTest for now. We support building for multiplatform, but won't support
        # deploying to iOS (native) will be supported once the new Kotlin/Native memory and
        # threading model is released.
        run: ./gradlew --no-daemon clean check -x nativeTest

      # Error out if any files were left dirty as the result of running the above.
      - name: Check for dirty files
        run: test -z "$(git status --porcelain)" || (echo "Changed files:" && git status --porcelain && exit 1)
