name: Pull Request Checks
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Commit check
        uses: docker://aevea/commitsar:latest

      - name: Code Check
        run: ./gradlew --no-daemon clean check
