name: Pull Request Checks
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Verify Conventional Commit format
        uses: docker://aevea/commitsar:latest

      - name: Code Check
        run: ./gradlew --no-daemon clean check dokkaHtml

      # Error out if any files were left dirty as the result of running the above.
      - name: Check for dirty files
        run: test -z "$(git status --porcelain)" || (echo "Changed files:" && git status --porcelain && exit 1)
